name: Build, Push and Deploy to Rancher (externo)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.OCI_REGION }}
          username: ${{ secrets.OCI_USER }}
          password: ${{ secrets.OCI_PASS }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.OCI_REGION }}/${{ secrets.OCI_NAMESPACE }}/poc/image/teste:latest

  deploy:
    runs-on: [self-hosted, dkr-surf-externo]
    needs: build
    steps:
      - name: Force Docker Pull (garantir imagem mais recente)
        run: |
          IMAGE="${{ secrets.OCI_REGION }}/${{ secrets.OCI_NAMESPACE }}/poc/image/teste:latest"
          echo "🔄 Forçando docker pull da imagem $IMAGE"
          docker pull "$IMAGE" || true

      - name: Deploy to Rancher 1.6 (externo)
        run: |
          set -euo pipefail
          IMAGE="${{ secrets.OCI_REGION }}/${{ secrets.OCI_NAMESPACE }}/poc/image/teste:latest"
          NAME="app-poc-teste"
          PROJECT_ID="1a120"

          echo "✅ Usando PROJECT_ID=$PROJECT_ID"
          echo "🔎 Verificando se container $NAME já existe..."

          CONTAINERS=$(curl -s -u "${{ secrets.RANCHER_ACCESS_KEY }}:${{ secrets.RANCHER_SECRET_KEY }}" \
            "${{ secrets.RANCHER_URL }}/v2-beta/projects/$PROJECT_ID/containers")
          CONTAINER=$(echo "$CONTAINERS" | jq -r ".data[] | select(.name==\"$NAME\")")

          if [ -n "$CONTAINER" ] && [ "$CONTAINER" != "null" ]; then
            CONTAINER_ID=$(echo "$CONTAINER" | jq -r ".id")
            OLD_IMAGE=$(echo "$CONTAINER" | jq -r ".imageUuid" | sed 's/^docker://')

            echo "📦 Container $NAME já existe (ID=$CONTAINER_ID)"
            echo "Imagem atual: $OLD_IMAGE"
            echo "Nova imagem: $IMAGE"

            if [ "$OLD_IMAGE" = "$IMAGE" ]; then
              echo "ℹ️ Imagem já está na versão mais recente. Nenhuma atualização necessária."
              exit 0
            fi

            echo "⬆️ Atualizando imagem do container..."
            curl -s -u "${{ secrets.RANCHER_ACCESS_KEY }}:${{ secrets.RANCHER_SECRET_KEY }}" \
              -X PUT "${{ secrets.RANCHER_URL }}/v2-beta/projects/$PROJECT_ID/containers/$CONTAINER_ID" \
              -H 'Content-Type: application/json' \
              -d "{
                \"imageUuid\": \"docker:$IMAGE\",
                \"restartPolicy\": {\"name\": \"always\"},
                \"alwaysPullImage\": true
              }"

            echo "⏳ Aguardando container subir..."
            for i in {1..12}; do
              STATUS=$(curl -s -u "${{ secrets.RANCHER_ACCESS_KEY }}:${{ secrets.RANCHER_SECRET_KEY }}" \
                "${{ secrets.RANCHER_URL }}/v2-beta/projects/$PROJECT_ID/containers/$CONTAINER_ID" | jq -r ".state")
              echo "   -> Tentativa $i: status=$STATUS"
              if [ "$STATUS" = "running" ]; then
                echo "✅ Deploy atualizado com sucesso."
                exit 0
              fi
              sleep 5
            done

            echo "⚠️ Deploy não chegou em estado running. Fazendo rollback para imagem antiga: $OLD
