name: Build and Push Docker image

on:
  push:
    branches: ["main"]
  
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-docker-demo:latest .

      - name: Push para Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-docker-demo:latest
