name: Build and Push to OCI Registry

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to OCIR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.OCI_REGION }}    # ex.: gru.ocir.io
          username: ${{ secrets.OCI_USER }}      # ex.: meutenancy/usuario
          password: ${{ secrets.OCI_PASS }}      # Auth Token gerado no OCI

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.OCI_REGION }}/${{ secrets.OCI_NAMESPACE }}/minha-app:latest
            ${{ secrets.OCI_REGION }}/${{ secrets.OCI_NAMESPACE }}/minha-app:${{ github.sha }}