name: Build and Push to OCI Registry

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to OCIR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.OCI_REGION }}    # ex.: gru.ocir.io
          username: ${{ secrets.OCI_USER }}      # ex.: grj71pgur80e/usuario@empresa.com
          password: ${{ secrets.OCI_PASS }}      # Auth Token

      - name: Define image name
        id: vars
        run: |
          IMAGE_NAME="${{ secrets.OCI_REGION }}/${{ secrets.OCI_NAMESPACE }}/stage/frontend_teste/frontend_pdv"
          IMAGE_TAG="build-${GITHUB_RUN_NUMBER}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "📦 Imagem será: $IMAGE_NAME:$IMAGE_TAG"

      - name: Build and Push Docker image (multi-stage)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Show pushed image
        run: |
          echo "✅ Imagem publicada com sucesso:"
          echo "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          echo "${{ env.IMAGE_NAME }}:latest"
